server:
  port: 8082

spring:
  application:
    name: rest-api
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:cars
  jpa:
    generate-ddl: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:8081/oauth2/jwks

client:
  url: http://localhost:8080